name: flutter_template
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_route: ^4.1.0
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  dio: ^4.0.6
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^1.0.3
  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.1
  import_sorter: ^4.6.0
  intl: ^0.17.0
  oauth2: ^2.0.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  responsive_framework: ^0.2.0
  riverpod: ^1.0.3
  sentry_flutter: ^6.6.1
  webview_flutter: ^3.0.2
  mocktail: ^0.3.0
  sembast: ^3.2.0
  path_provider: ^2.0.9
  flash: ^2.0.3+2
  cached_network_image: ^3.2.0
  sembast_web: ^2.0.1+1
  platform: ^3.1.0


dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.8
  derry: ^1.4.3
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.5
  very_good_analysis: ^3.0.1
  test: ^1.19.5

scripts: derry.yaml

flutter:
  uses-material-design: true
